# permissions for end users to edit mysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mysql-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mysql
    app.kubernetes.io/part-of: mysql
    app.kubernetes.io/managed-by: kustomize
  name: mysql-editor-role
rules:
- apiGroups:
  - tool.liuxiangbiao.com
  resources:
  - mysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tool.liuxiangbiao.com
  resources:
  - mysqls/status
  verbs:
  - get
